[keyboard]
name = "CCK"
product_name = "CCK"
vendor_id = 0x1313
product_id = 0x1717
manufacturer = "WK"
chip = "nrf52840"

[layout]
rows = 5
cols = 12
layers = 10
keymap = [
    [
        ["_", "_", "_", "_", "_", "_",     "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_",     "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_",     "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_",     "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_",     "_", "_", "_", "_", "_", "_"]
    ],
]

[storage]
# # Storage feature is enabled by default
# enabled = true
# clear_storage = true

[ble]
enabled = true
battery_adc_pin = "vddh"

[light]

# default profile for morse, tap dance and tap-hold keys:
# [behavior.morse]
# enable_flow_tap = false
# hold_timeout = "200ms"
# gap_timeout = "200ms"
# prior_idle_time = "50ms"
# hold_on_other_press = false

[split]
connection = "ble"

[split.central]
rows = 5
cols = 6
row_offset = 0
col_offset = 0
# ble_addr = [0x18, 0xe2, 0x21, 0x80, 0xc0, 0xc7]

[split.central.matrix]
matrix_type = "normal"
row_pins = ["P0_11", "P1_00", "P0_24", "P0_22", "P1_13"]
col_pins = ["P1_15", "P0_09", "P0_10", "P1_11", "P1_04", "P1_06"]

# Encoder 0
[[split.central.input_device.encoder]]
pin_a = "P0_29"
pin_b = "P0_02"
phase = "resolution"
resolution = 2
internal_pullup = true
reverse =  false

[[split.peripheral]]
rows = 5
cols = 6
row_offset = 0
col_offset = 6
# ble_addr = [0x7e, 0xfe, 0x73, 0x9e, 0x66, 0xe3]

[split.peripheral.matrix]
matrix_type = "normal"
row_pins = ["P0_11", "P1_00", "P0_24", "P0_22", "P1_13"]
col_pins = ["P1_15", "P0_09", "P0_10", "P1_11", "P1_04", "P1_06"]

# Encoder 1
[[split.peripheral.input_device.encoder]]
pin_a = "P0_29"
pin_b = "P0_02"
phase = "resolution"
resolution = 2
internal_pullup = true
reverse =  false

[rmk]
combo_max_num = 32
morse_max_num = 32
mouse_wheel_interval = 40  # 滚动间隔（毫秒），默认 80ms

[host]
# Unlock combination: simultaneous press of specified keys
# Format: [[row, col], [row, col], ...]
unlock_keys = [[2, 1], [2, 2]]  
